eGuide/config/routes.rb
Rails.application.routes.draw do
	resources :standards do 
		collection { post :create }
		member { get :save }
	end
	root to: "standards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eGuide/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eGuide/app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :standard
  	# this model's methods take the key value pairs from the submittted csv to make guides
  	# by comparing scores to domains,choosing the next domain without demonstrated compentency
  	# as a learning track in string form for saving to csv format.

  def make_guide(tests, hashed_domains, max = 5, size = 0)
  	catch :completed do
      hashed_domains.each do |key,val|
        val.each do |domain|
          if tests[domain].to_i <= key.to_i
            stringify(key, domain)
            throw :completed if (size += 1) == max
          end
        end
      end
  	end
  end

  def stringify(year, domain)
  	string = "#{year}.#{domain}"
  	 if self.path.nil?
        self.path = string
      else
        self.path << "," + string
      end 
    end

end

eGuide/app/models/standard.rb
require 'csv'


class Standard < ApplicationRecord
	has_many :guides
	# this model's methods parse and put in key value pairs the submittted csv files.

	def run
		standardized_tests.each do |test|
			guide = guides.create(student: test["Student Name"])
			guide.make_guide(test, hashed_domains)
			guide.save!
		end
	end


	def hashed_domains
		domain = {}
		CSV.parse(domains).each do |row|
			domain[row.shift] = row
		end
		domain
	end

	def standardized_tests
		tested = []
		CSV.parse(tests, headers: true) do |row|
			tested << row.to_hash
		end
		tested
	end

	def save_csv
		file = CSV.generate do |csv|
			guides.each do |s| 
				csv << s.student.parse_csv + s.path.parse_csv
			end
		end
		file
	end


end

eGuide/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

eGuide/app/controllers/standards_controller.rb
require 'csv'


class StandardsController < ApplicationController

  def index
    @standards = Standard.all
  end

  def show
    @standard = Standard.find(params[:id])
  end

  def create
    domains = params[:domains]
    tests = params[:tests]

    @standard = Standard.new({domains: domains.read, tests: tests.read})
    invalid = domains.nil? || tests.nil?

    if !invalid && @standard.save
      @standard.run
      flash[:success] = "Guide created"
    else
      flash[:error] = "Try again"
    end
    redirect_to :back
  end


  def save
    @standard = Standard.find(params[:id])
    respond_to do |format|
      format.csv { send_data @standard.save_csv }
  end
end

  def destroy
    Standard.find(params[:id]).destroy
    flash[:success] = "Guide deleted"
    redirect_to standards_url
  end

  private

  def standard_params
    params.require(:standard).permit(:tests, :domains)
  end

end

eGuide/app/helpers/application_helper.rb
module ApplicationHelper
end

eGuide/app/helpers/standards_helper.rb
module StandardsHelper
end

eGuide/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EGuide</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="container">
	  	<% flash.each do |msg_type, msg| %>
	  		<div class="alert alert-<%= msg_type%>"><%= msg %></div>
	  	<% end %>
	    <%= yield %>
	  </div>
  </body>
</html>

eGuide/app/views/standards/index.html.erb
<h1>Welcome to your Guide maker!</h1>
<p>Please import your csv files of tests and domains here.</p>

<%= form_for :standard, url: standards_path, html: { multipart: true } do %>
	<div class="field">
	    <label>Tests in CSV format </label><br>
	    <%= file_field_tag :tests %>
	 </div>
	 <div class="field">
	  <label>Domains in CSV format</label><br>
	    <%= file_field_tag :domains %>
	 </div>
	 <div class="actions" >
	    <%= submit_tag "Create Guide" %><br>
	 </div>
<% end %>

<div class="row">
	<div class="list">
		<h2>Here are the available Guides:</h2>

			<% @standards.each do |standard|  %>
				<ol>
					<strong>Guide number: <%= standard.id %></strong>
					, created at <%= standard.created_at.strftime("%I:%M%p %m/%d") %>
					<%= link_to 'Save CSV', save_standard_path(id: standard.id, format: "csv") %>
					<%= link_to "Show", standard %>
					<%= link_to "Delete", standard, method: :delete %>
					
				</ol>
			<% end %>

	</div>
</div>

eGuide/app/views/standards/show.html.erb
<h1>Standards</h1>
<p>Here are the tracks for each student:</p>


<% @standard.guides.each do |track| %>

<h4><%= track.student %></h4>
<p><%= track.path %></p>
<% end %>

<%= link_to "Back to Home", root_url %>